### ISSUE TITLE
ssl in saas multi domain

### ISSUE THREAD

**Issue by vahidalvandi** [acaranta/certbot-autorenew#1]
hi
I have a saas system in which the user can define other domains. And by setting the saas server ip on any domain with ssl, it can see saas.
After much research, I came to the conclusion that haproxy can solve this problem  . do this package can solve my problem??

**Comment by acaranta** [comment]
To be honest I don't know ... this container is a custom version of cerbot to renew my certs, and copying the cert files to a specific directory on my servers, and a custom haproxy container I use has inotify checks to reload the configuration ...
